### ISSUE TITLE
Document close-wait-timeout annotation

### ISSUE THREAD

**Issue by muenchdo** [linkerd/website#1048]
The `close-wait-timeout` option that was introduced in linkerd/linkerd2#4409 is not yet documented on the [proxy configuration](https://linkerd.io/2.10/reference/proxy-configuration) page. The file driving the content for this page seems to be autogenerated, so I didn't know where to adjust this.

**Comment by alpeb** [comment]
Good catch :+1: 
If you'd like to contribute a fix, the place to do it is in https://github.com/linkerd/linkerd2/blob/main/cli/cmd/doc.go :wink:
