### ISSUE TITLE
Hyperlinks in docs do not render correctly - Staging microservices without the tears

### ISSUE THREAD

**Issue by rdileep13** [linkerd/website#1118]
Noticed that the hyperlink does not render correctly for this link - https://linkerd.io/2017/01/07/a-service-mesh-for-kubernetes-part-vi-staging-microservices-without-the-tears/

Looks like there is a missing parenthesis that's causing this issue in the file linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-vi-staging-microservices-without-the-tears.md

I cannot get to the line numbers, so I cannot point to the exact line but here is the snippet:

>>
[Staging microservices without the tears]({{< ref "a-service-mesh-for-kubernetes-part-vi-staging-microservices-without-the-tears" >}} (this article)
<<
This is missing a parenthesis before "(this article)" based on the observation

**Comment by rdileep13** [comment]
Opened a PR at https://github.com/linkerd/website/pull/1120

I tried to resolve DCO by adding 'Signed Off... '. It didn't seem to work..

Please also excuse my naive issues with git. I am getting started with git now. It's a bit confusing to say the least

**Comment by cpretzer** [comment]
Thanks for trying to resolve the DCO @rdileep13 ! You're not the first person to run into this, so a couple of options were added to the DCO sign-off [requirements](https://github.com/linkerd/linkerd2/blob/main/CONTRIBUTING.md#option-2-public-statement)

I can push the merge through based on the guidelines in that doc 😄

**Comment by adleong** [comment]
Thank you!
