### ISSUE TITLE
Change "cluster" to "cross-cluster" in multicluster blog

### ISSUE THREAD

**Issue by importhuman** [linkerd/website#1157]
In the [Multicluster Kubernetes with Service Mirroring](https://linkerd.io/2020/02/25/multicluster-kubernetes-with-service-mirroring/#service-mirroring) blog, the first paragraph of the "Service mirroring" section has this line:

> ...With service mirroring in place, the full observability, security, and routing features of Linkerd apply uniformly to both in-cluster and **cluster-calls**... 

From context, I think it should be "cross-cluster calls" at the end instead. I'd be happy to submit a PR if required.

**Comment by cpretzer** [comment]
good catch @importhuman! We'd love a PR to fix that
