### ISSUE TITLE
Incorrect version in tasks/multicluster-using-statefulsets

### ISSUE THREAD

**Issue by importhuman** [linkerd/website#1183]
The [prerequisites of the blog](https://linkerd.io/2.10/tasks/multicluster-using-statefulsets/#prerequisites) mention 
> linkerd:stable-2.11.0 to install Linkerd

but the latest stable release is 2.10.2. Is this deliberate? 

Happy to submit a PR if required.

**Comment by alpeb** [comment]
@mateiidavid That page refers to functionality coming in 2.11, right? If so, could you move that to the `2.11` dir?

**Comment by alpeb** [comment]
Thanks for the heads up @importhuman , the fix was just a matter of removing that from the 2.10 directory, as the upcoming 2.11 one already has it, which has already been taken care of :+1:
