### ISSUE TITLE
change linkerd-collector.linkerd to collector.linkerd-jaeger

### ISSUE THREAD

**Issue by FingerLiu** [linkerd/website#1249]
since jaeger change to plugin, we should change all refer of  `linkerd-collector.linkerd` to `collector.linkerd-jaeger` globally.
https://linkerd.io/2.11/tasks/distributed-tracing/
![image](https://user-images.githubusercontent.com/3981064/144591486-acce533b-66a9-4e80-9dfd-a2e4ed1bda0b.png)

**Comment by cpretzer** [comment]
@FingerLiu that's a great point. Would you mind submitting a PR for those changes?

**Comment by FingerLiu** [comment]
Sure.
