### ISSUE TITLE
Install script error in `curl` invocation

### ISSUE THREAD

**Issue by shousper** [linkerd/website#1282]
Hi 👋🏻 

As of [this commit](https://github.com/linkerd/website/commit/6f6ae6e3115ebc8464f27cc504357e7e13598e58) we are seeing the following error when attempting to install `linkerd` using the install script:

```
Downloading linkerd2-cli-stable-2.11.1-linux-amd64...
curl: option --proto==https: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```

I believe the issue is merely the use of `=` instead of a space with the `--proto` option in [the install script `run.linkerd.io/public/install`](https://github.com/linkerd/website/commit/6f6ae6e3115ebc8464f27cc504357e7e13598e58#diff-2f52d41b0c6ae8fafe84c563ef2dc64797c1fb1f2a625f293416783beccd6304).

**Comment by olix0r** [comment]
@shousper Thanks for the report!
