### ISSUE TITLE
Proxy configuration reference refers to cli table

### ISSUE THREAD

**Issue by baracoder** [linkerd/website#1297]
The table of proxy annotations lists linkerd sub-commands
https://linkerd.io/2.11/reference/proxy-configuration/
![Screenshot from 2022-02-03 14-56-07](https://user-images.githubusercontent.com/127523/152356687-694ac5d6-de4e-4060-b7d9-79a17d45ae88.png)

**Comment by alpeb** [comment]
Oops, thanks for the report! I'll get this fixed ASAP!

**Comment by baracoder** [comment]
That is quick, thank you.
