### ISSUE TITLE
Where to update Linkerd1 docu?

### ISSUE THREAD

**Issue by peterfroehlich** [linkerd/website#13]
I want to create a docu pr for the new zipkin trace propagation plugin. 
Where do I find it?
 
The README in this repo says 'https://github.com/linkerd/website/blob/master/slate-linkerd' which 404es. 
The build file in website/api.linkerd.io/build states 'https://github.com/BuoyantIO/slate-linkerd.git' which is either private or nonexistent. 

Thanks
Peter

**Comment by dadjeibaah** [comment]
@peterfroehlich the usual way we add docs to https://api.linkerd.io/1.4.x/linkerd is to update or create one of the YAML files located [here](https://github.com/linkerd/linkerd/tree/master/linkerd/docs). Then, on next release, any new docs that have been added are picked up and published to linkerd.io

**Comment by klingerf** [comment]
Thanks for bringing this to our attention, @peterfroehlich! We should use this issue to track removing references to the slate repo, which is outdated. As @dadjeibaah mentioned, the linkerd1.x docs live in the [linkerd/linkerd](https://github.com/linkerd/linkerd) repo itself.

**Comment by peterfroehlich** [comment]
You are welcome. :) As for the doc update, I opend a Pull request -> https://github.com/linkerd/linkerd/pull/2123
