### ISSUE TITLE
Add text describing 'multicluster link' is a unidirectional connection

### ISSUE THREAD

**Issue by shmcfarl** [linkerd/website#1304]
Please add some text for the 'multicluster' command [https://linkerd.io/2.11/reference/cli/multicluster/](https://linkerd.io/2.11/reference/cli/multicluster/) as well as the [https://linkerd.io/2.11/tasks/multicluster/](https://linkerd.io/2.11/tasks/multicluster/) page that explains that the "linkerd --context=<ctx> multicluster link" command establishes a one way link. If the user wants to export services in both directions, they have to establish a link in both directions.

**Comment by kleimkuhler** [comment]
This has been updated in the 2.12 [docs](https://linkerd.io/2.12/reference/cli/multicluster/#link).
