### ISSUE TITLE
CLI doc updates for `linkerd viz stat` (interactions between HttpRoute/ServiceProfile/AuthorizationPolicy)

### ISSUE THREAD

**Issue by jeremychase** [linkerd/website#1405]

**Comment by adleong** [comment]
We'll want to add HttpRoute, and AuthorizationPolicy to the list of resources that can be targeted.  This will require updating the description in cobra in the linkerd2 repo and then regenerating the `linkerd doc` docs.

**Comment by hawkw** [comment]
closed by linkerd/linkerd2#9242 and  #1439
