### ISSUE TITLE
CLI doc updates for `linkerd viz tap`?

### ISSUE THREAD

**Issue by jeremychase** [linkerd/website#1407]

**Comment by mateiidavid** [comment]
fwiw since there's a question mark in the title: as of [`edge-22.8.2`](https://github.com/linkerd/linkerd2/blob/main/CHANGES.md#edge-2282) we have policy metadata for tap output in json format

```json
      "srv_group": "policy.linkerd.io",
      "srv_kind": "server",
      "srv_name": "hokay-server",
      "tls": "loopback"

```

**Comment by kleimkuhler** [comment]
Nothing significant changed in the usage of `linkerd viz tap` so I'm closing this as the docs are up-to-date.
