### ISSUE TITLE
Task doc/example for setting route-based policy

### ISSUE THREAD

**Issue by jeremychase** [linkerd/website#1409]

**Comment by hawkw** [comment]
I wrote up this during testing, it probably could be turned into a "tasks" tutorial pretty easily: https://github.com/hawkw/routekicking#booksapp-demo

**Comment by wmorgan** [comment]
I would probably start by extending the existing task in https://linkerd.io/2.11/tasks/restricting-access/ rather than starting a new doc, unless that gets really unwieldy.

**Comment by hawkw** [comment]
@wmorgan that doc uses Emojivoto, while the per-route authz walkthrough I wrote needs to use booksapp, as emojivoto doesn't currently contain multiple services that send requests to different routes on a third service.

**Comment by wmorgan** [comment]
Ok, do what's easy for now. We probably need to merge these two later but we can handle that, well, later.

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/website/pull/1426
