### ISSUE TITLE
document the fact that AuthorizationPolicies can attach to namespaces

### ISSUE THREAD

**Issue by wmorgan** [linkerd/website#1446]
It's cool

**Comment by wmorgan** [comment]
We have an example now, but I'd want to makes sure this is also captured in the reference section.

**Comment by kleimkuhler** [comment]
This example was added to the reference section. The sub-section that talks about `targetRef` is currently

```
### targetRef

`TargetRef` identifies an API object.

{{< table >}}
| field| value |
|------|-------|
| `group`| Group is the group of the target resource.|
| `kind`| Kind is kind of the target resource.|
| `namespace`| Namespace is the namespace of the target resource. When unspecified (or empty string), this refers to the local namespace of the policy.|
| `name`| Name is the name of the target resource.|
{{< /table >}}
```

Are you thinking you'd want that to explicitly call out Namespaces as being valid targets? I think saying "... identifies an API object" is already okay, but we can call out Namespaces if that's what you had in mind? That does lead me to think though what API objects we should or should not be explicit about in the docs.

**Comment by wmorgan** [comment]
I'll make a PR; there are some other changes I want to make to this doc.

**Comment by wmorgan** [comment]
#1484
