### ISSUE TITLE
Update the install instructions in the generating certificates tutorial

### ISSUE THREAD

**Issue by adleong** [linkerd/website#1454]
The installation instructions in https://linkerd.io/2.12/tasks/generate-certificates/#passing-the-certificates-to-linkerd are out of date for both CLI and Helm methods.

The CLI instructions should be updated to include the `install --crds` step.

The Helm instructions should be updated to reference the `linkerd-crds` chart.

**Comment by hawkw** [comment]
https://github.com/linkerd/website/pull/1449 should fix this, modulo the helm instructions, which i'll update now
