### ISSUE TITLE
Test for dead links

### ISSUE THREAD

**Issue by grampelberg** [linkerd/website#149]
It is pretty easy to introduce dead links, CI should check for internal inconsistencies as well as the search index. A tool to check for dead links:

https://github.com/wjdp/htmltest

**Comment by grampelberg** [comment]
I've got a Makefile target for this now. Automating it would be awesome. In a perfect world there would also be SreamingFrog integration to get the search console results and make sure we're not invalidating any cache.

**Comment by lucperkins** [comment]
Fair warning: this tool has *never* worked for me. I've never been able to use it without getting weird segfault-y errors, and that's when it actually completes and doesn't just silently hang. I'd recommend [html-proofer](https://github.com/gjtorikian/html-proofer) instead. I can implement that if you'd like.
