### ISSUE TITLE
Netlify: select a new build image

### ISSUE THREAD

**Issue by nate-double-u** [linkerd/website#1507]
Notice from Netlify
> After November 15, 2022, builds for this site will fail unless you [update the build image](https://app.netlify.com/sites/cloudevents-io/settings/deploys#build-image-selection).

**Comment by nate-double-u** [comment]
It looks like there are only CNCF members on the Netlify team for this site. We can help manage this issue, but there should probably be a linkerd maintainer on the Netlify team as well.

**Comment by nate-double-u** [comment]
Just wanted to bump this.
* @olix0r
* @adleong
* @zaharidichev
* @hawkw
* @alpeb
* @kleimkuhler
* @pothulapati

**Comment by wmorgan** [comment]
@nate-double-u thanks for the ping. I believe the way this site works today is that Github actions does the actual building, but we rely on Netlify for preview links and possible some integration tests.

Please add @kflynn @olix0r and myself to the netlify team for the site for awareness.

Am I to understand that you are taking on the build image change?

**Comment by nate-double-u** [comment]
> Am I to understand that you are taking on the build image change?

I can help with it if you'd like, but I'd prefer that Netlify be setup so that the maintainers/contributors can manage the site in a more self serve manner.

Could you send me the email addresses of the folks i should add to the Netlify Team? (either here or in the CNCF slack)

**Comment by nate-double-u** [comment]
Image is updated, and a test deploy successful: https://app.netlify.com/sites/linkerd/deploys/637d0b9405f94206c78bdc5a

<img width="923" alt="Screenshot 2022-11-22 at 9 46 53 AM" src="https://user-images.githubusercontent.com/4453979/203385089-3eaaad69-1f6a-494f-8f07-92f80605318a.png">

We should still workout who should be added to the Netlify account from the Linkerd project 🙂

**Comment by wmorgan** [comment]
@nate-double-u Sorry I dropped the ball on this. I'll send you the emails on the CNCF slack.

**Comment by nate-double-u** [comment]
Invites sent!
Closing this issue as complete.

**Comment by wmorgan** [comment]
Thank you @nate-double-u !
