### ISSUE TITLE
Add Xbox case study to adopters list

### ISSUE THREAD

**Issue by CathPag** [linkerd/website#1527]
Please feature [Xbox's case study](https://buoyant.io/case-studies/xbox) on the top of the [Linkerd adopter's page](https://linkerd.io/community/adopters/). Place it first if possible.

**Comment by sergioarmgpl** [comment]
@CathPag I want to work on this.

**Comment by CathPag** [comment]
Thanks, Sergio. It has actually already been done but the issue wasn't closed, so I'll do that now.
