### ISSUE TITLE
document HTTPRoute/ServiceProfile outbound policy incompatibility

### ISSUE THREAD

**Issue by hawkw** [linkerd/website#1608]
currently, proxies will only honor outbound policy configuration from ServiceProfiles _or_ from the OutboundPolicies API (HTTPRoutes/failure accrual annotations). the documentation never actually states this, so users may be surprised to discover that their circuit breaking or dynamic request routing configurations don't work when a ServiceProfile already exists for that service.

we should document this to help users avoid confusion.

**Comment by risingspiral** [comment]
Make internal doc first

**Comment by hawkw** [comment]
Internal doc: https://www.notion.so/buoyantio/Client-Policies-vs-Service-Profiles-99b378fc08ff4414941177961579be88?pvs=4

**Comment by hawkw** [comment]
https://github.com/linkerd/website/pull/1613

**Comment by hawkw** [comment]
fixed in https://github.com/linkerd/website/commit/70b5a4c6ce574dc52a96d4b3b870c4dda156805c
