### ISSUE TITLE
update supported K8s versions page for edge releases

### ISSUE THREAD

**Issue by wmorgan** [linkerd/website#1746]
We should include edge releases in the [supported K8s versions page](https://linkerd.io/2.15/reference/k8s-versions/) .

**Comment by wmorgan** [comment]
@kflynn Please tackle this after #1775

**Comment by wmorgan** [comment]
We can start with the 2.15+ edge releases (probably a single-row table) since that's where the focus has really been.

**Comment by kflynn** [comment]
Oops, this is done as of awhile ago (cf #1792 et al).
