### ISSUE TITLE
versioncheck.linkerd.io/update redirect to non https

### ISSUE THREAD

**Issue by SamClinckspoor** [linkerd/website#2]
/kind bug

https://versioncheck.linkerd.io/update has a redirect to a non-https url.
It looks like an https version of the url is also available but not part of the redirect chain.

(note **location: http://versioncheck.linkerd.io/update/index.html**

```bash
curl -I https://versioncheck.linkerd.io/update
HTTP/2 301
date: Thu, 23 Aug 2018 12:35:42 GMT
content-type: text/html; charset=UTF-8
set-cookie: __cfduid=d93f2e19bbe81933b17ee40ce6c061f1b1535027742; expires=Fri, 23-Aug-19 12:35:42 GMT; path=/; domain=.linkerd.io; HttpOnly
x-guploader-uploadid: AEnB2UrDXQUnzG-sg9ChsATKHDk1tEI5EXPXnADLKloz3IJVk8vE_wg7_nPinZLgd4x-fKkppxblfW21GRSLHxmYh4aCVmjESQ
location: http://versioncheck.linkerd.io/update/index.html
vary: Origin
expires: Thu, 23 Aug 2018 12:35:42 GMT
cache-control: private, max-age=0
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 44ed9edc09334415-BRU
```

**Comment by wmorgan** [comment]
Thanks @SamClinckspoor!

**Comment by grampelberg** [comment]
Google in their infinite wisdom does a redirect to http for `index.html` content. I can't fix the redirect mentioning http, but there's an always redirect to https rule now in place. I'll keep my eyes open if we end up on another hosting solution to make sure they don't do something funky like this.
