### ISSUE TITLE
Websockets failing for top/tap on linkerd dashboard ingress thru nginx ingress controller

### ISSUE THREAD

**Issue by gamer22026** [linkerd/website#211]
### What is the issue?
After setting up an ingress (kubernetes/ingress-nginx) for linkerd dashboard, there are websocket errors and neither top nor tap work. We use the same ingress controller for our own websocket based app so it doesn't appear to be an issue with the ingress controller handling websocket traffic.
### Logs, error output, etc
From linkerd-web logs:
```
time="2019-03-01T21:01:32Z" level=error msg="websocket: 'Origin' header value not allowed"
2019/03/01 21:01:32 http: multiple response.WriteHeader calls
```

#### `linkerd check` output

```
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus

linkerd-service-profile
-----------------------
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.10.11
- Cluster Environment: kops
- Host OS: Debian Jessie
- Linkerd version: 19.2.5

### Additional context
https://github.com/linkerd/linkerd2/issues/2143

**Comment by phxql** [comment]
For completeness: I ran into the same problem when exposing the Linkerd dashboard through a keycloak gatekeeper.

I fixed it with these commandline flags:

```
--headers=Host=linkerd-web.linkerd.svc.cluster.local:8084
--headers=Origin=http://linkerd-web.linkerd.svc.cluster.local:8084
```
