### ISSUE TITLE
Document inject override annotations

### ISSUE THREAD

**Issue by klingerf** [linkerd/website#222]
In linkerd/linkerd2#2471, we added support for overriding inject configuration options via annotations on a workload's pod spec. We should document all of these annotations somewhere on the website, as they're not intuitable.

**Comment by alpeb** [comment]
We also need to describe how uninjection/black-listing is supposed to work now with annotations, and add a note about the special case of orphaned pods (see this [comment](https://github.com/linkerd/linkerd2/issues/2338#issuecomment-478080553)).

**Comment by ihcsim** [comment]
IIRC, the decision is to leave all the `config.linkerd.io/*` annotations alone during uninject, since they are user-provided annotations.

**Comment by alpeb** [comment]
Agreed about `config.linkerd.io` annotations. I had only in mind `linkerd.io/inject` and how it would trigger or disable injection. Strictly speaking it's a different topic than "override annotations" referred in this issue. So not sure if should be treated in a separate section in the docs, or as section within this topic...

**Comment by ihcsim** [comment]
I think general behaviour of `linkerd.io/inject` can go under the "automating injection" doc. We don't have anything specific for uninject though.

**Comment by ihcsim** [comment]
Per https://github.com/linkerd/website/issues/222, document a way for user to override the control plane's proxies log level, without affecting the global default. The current approach is to use `kubectl edit` to modify the `LINKERD2_PROXY_LOG` env var.
