### ISSUE TITLE
Add 2.3 Upgrade Instructions

### ISSUE THREAD

**Issue by ihcsim** [linkerd/website#235]
Update the _Upgrading Linkerd_ docs to include upgrade notice for 2.3. 

Specifically, we need to inform the users during the first upgrade (from 2.2.x to 2.3), all the previously-provided install flags need to be included in the `linkerd upgrade` command. For example, if `--proxy-auto-inject` was provided during install, it must also be included during the first upgrade. Otherwise, the proxy injector won't be upgraded and it would still be using the old protobuf.

**Comment by siggy** [comment]
Fixed as part of #236 and #262
