### ISSUE TITLE
a google search for "linkerd getting started" doesn't have /2/getting-started anywhere in the first page

### ISSUE THREAD

**Issue by wmorgan** [linkerd/website#245]
It's all /1/ content. Why?

<img width="750" alt="image" src="https://user-images.githubusercontent.com/4026/55766987-d9761980-5a2b-11e9-9c28-cc77eafbd34f.png">

**Comment by klingerf** [comment]
I wonder if it's an issue with our site map (https://linkerd.io/sitemap.xml).

We've included priorities on many of the /2 pages. For instance:

```
<url>
  <loc>https://linkerd.io/2/getting-started/</loc>
  <priority>1</priority>
</url>
```

But most URLs (including all of the /1 pages) don't have the priority field set. Maybe they're being interpreted as higher priority? That would surprise me, though.

**Comment by lucperkins** [comment]
Just as a data point, the v2 Getting Started guide comes up first for me

**Comment by wmorgan** [comment]
In a Firefox "private window", /2/getting-started also comes up first. Hm. Maybe this is just a case of Google Thinks They Know Best.

**Comment by grampelberg** [comment]
I get `/2/getting-started/` for both logged in and anonymous searches. Should we close this out? Is there an improvement we could make?

**Comment by wmorgan** [comment]
Yah let's chalk this up to PEBKAC
