### ISSUE TITLE
Community Update Promotion Request

### ISSUE THREAD

**Issue by kierstenlinkerd** [linkerd/website#260]
Please promote the following on the linkerd community update: 

On Wed, April 24 @ 10 am (PT), join Oliver and Thomas for our second-ever online Linkerd community meeting. We’ll chat about the Linkerd 2.3 release and the roadmap ahead. Sign up here: https://www.meetup.com/Linkerd-Online-Community-Meetup/events/260356731/

**Comment by siggy** [comment]
Fixed as part of #262
