### ISSUE TITLE
Link at prometheus.md pointing to old docs

### ISSUE THREAD

**Issue by obitech** [linkerd/website#27]
Link to the Proxy-Metrics in [prometheus.md](https://github.com/linkerd/website/blob/master/linkerd.io/content/2/prometheus.md) is dead and should link to https://github.com/linkerd/website/blob/master/linkerd.io/content/2/proxy-metrics.md instead.

**Comment by klingerf** [comment]
@obitech Thanks for reporting! Hopefully @grampelberg can address this as part of #26.
