### ISSUE TITLE
Controller architecture diagram is missing grafana

### ISSUE THREAD

**Issue by klingerf** [linkerd/website#29]
The new [architecture page](https://linkerd.io/2/architecture/) is great. Any chance we can update this architecture diagram to include a pod for grafana as well?

![control-plane](https://user-images.githubusercontent.com/9226/45836381-8d4ace00-bcc1-11e8-949f-46b17afd3aa3.png)

For completeness we might also want to include the ca pod, although that's optional at this point, and might be better served by a TLS-specific diagram.

**Comment by adleong** [comment]
Good catch.  Does the grafana pod communicate with anything other than prometheus?

**Comment by adleong** [comment]
The source for this diagram is here: https://docs.google.com/presentation/d/1x9S_GOULkGf_LgqJyIFJnvdABKdRDm3edj8KfoK7uiM/edit?usp=sharing

**Comment by klingerf** [comment]
Awesome, thanks @adleong. The grafana pod only communicates with prometheus, and the update to the diagram that you made to add the grafana pod looks correct to me. :shipit:

**Comment by klingerf** [comment]
I'm happy to re-export that graph and make the change in this repo if that works for you.

**Comment by adleong** [comment]
That sounds great, thanks!
