### ISSUE TITLE
Install script links to a page that does not exist

### ISSUE THREAD

**Issue by klingerf** [linkerd/website#341]
When installing the `linkerd` CLI via the install script, it prints:

> Looking for more? Visit https://linkerd.io/2/next-steps

But that page 404s. We should restore that page, or figure out a new page to link to and update the script.

**Comment by javaducky** [comment]
Was just going to write this up!  Given this is post-install, should the url be the "Step 2: Validate your Kubernetes cluster" in the Getting Started page?  I.e. https://linkerd.io/2/getting-started/#step-2-validate-your-kubernetes-cluster

**Comment by cpretzer** [comment]
This was fixed [here](https://github.com/linkerd/linkerd2/commit/bd702b99ae808cd6ab450467e110ae8cef94c9f2#diff-f9d6a643590779e988564f9ab5c196caR11)
