### ISSUE TITLE
Linkerd dashboard community page request

### ISSUE THREAD

**Issue by kierstenlinkerd** [linkerd/website#346]
Please promote the following on the linkerd dashboard community page:

Subject: Join us: Linkerd community meeting on June 27, 9 am

On Thurs, June 27 @ 9 am (PT), join Oliver, Thomas, and special guest Jason Hansen (Microsoft) for this month’s Linkerd community meeting. We’ll chat about Linkerd 2.4, Kinvolk's Linkerd and Istio benchmarks, Microsoft's Service Mesh Interface, and Linkerd 2.5 and beyond.

Sign up: https://www.meetup.com/Linkerd-Online-Community-Meetup/events/262208328/

**Comment by grampelberg** [comment]
@kierstenlinkerd can you try using forestry for this now?

**Comment by kierstenlinkerd** [comment]
@grampelberg I meant the actual Linkerd dashboard, not the website. On the Linkerd dashboard, we added a promotional section. Can we post the community meeting there?

**Comment by grampelberg** [comment]
That's supposed to be in forestry now.

**Comment by kierstenlinkerd** [comment]
The feature is not set up in forestry yet. So that we don't lose precious promotional time, would someone mind posting it this time and next time I should be able to update this through Forestry?

**Comment by grampelberg** [comment]
@scottcarol mind taking this one?

**Comment by klingerf** [comment]
I've posted the update in #357.
