### ISSUE TITLE
Add 2.4 upgrade notes

### ISSUE THREAD

**Issue by ihcsim** [linkerd/website#349]
Use this task to capture the 2.4 upgrade notes.

### Tap RBAC bug

- [x] Done

If the users encountered:
```
The ClusterRoleBinding "linkerd-linkerd-tap" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"linkerd-linkerd-tap"}: cannot change roleRef
```
they will need to manually delete the `linkerd-linkerd-tap` cluster role binding, and re-run upgrade again. They will run into this issue only if they have previously installed edge-19.5.3 on the same cluster. This bug was fixed in edge-19.5.4.

### Webhook Side-effect

- [x] Done

For k8s pre-1.12, upgrade has to be performed with the `--omit-webhook-side-effects` flag, because the `sideeffect` property of the MWC and VWC is only supported by k8s 1.12+.

### Upgrade check

- [x] Done

If the user runs`linkerd check` against an older control plane, the check will fail complaining that the cluster roles don't exist. This is ok because the `check` command now relies on the label to determine if the RBAC resources exist.
```
linkerd version
Client version: edge-19.6.4
Server version: stable-2.3.2
➜  linkerd2 git:(master) ✗ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
× control plane ClusterRoles exist
    missing ClusterRoles: linkerd-linkerd-controller, linkerd-linkerd-identity, linkerd-linkerd-prometheus, linkerd-linkerd-proxy-injector, linkerd-linkerd-sp-validator, linkerd-linkerd-tap
    see https://linkerd.io/checks/#l5d-existence-cr for hints
```
The `check` will succeed after upgrade is completed.

### HA Setup

- [x] Done

The MWC and VWC will be configured with `FailurePolicy` to `fail`. Make sure that there are more than one proxy injector and sp validator.

### From Manifest

- [x] Done

Make sure this still works with the new proxy injector and sp validator secrets

**Comment by kleimkuhler** [comment]
Closed in https://github.com/linkerd/website/pull/396
