### ISSUE TITLE
Broken CSS on the community update page

### ISSUE THREAD

**Issue by klingerf** [linkerd/website#358]
It looks like the linkerd.io site update modified the CSS that we were using to display the community updates page. It now looks like this:

![image](https://user-images.githubusercontent.com/9226/59791139-47d62400-9286-11e9-8623-5fa9df2d65d5.png)

@scottcarol is going to investigate.

**Comment by wmorgan** [comment]
Oops! Thanks @scottcarol @klingerf!

**Comment by scottcarol** [comment]
Closed by #361
