### ISSUE TITLE
Update troubleshooting guide to include new 2.4 checks

### ISSUE THREAD

**Issue by ihcsim** [linkerd/website#372]
Update the troubleshooting guide to include new checks introduced to the `linkerd check` command.

Make sure the following hint anchors point to the correct docs:

* `pre-l5d-existence`
* `l5d-existence-mwc`
* `l5d-existence-vwc`
* `l5d-existence-psp`
* `l5d-existence-linkerd-config`
* `l5d-linkerd-config-not-exists`
* `l5d-existence-unschedulable-pods`

Follow up of https://github.com/linkerd/linkerd2/pull/2987 and https://github.com/linkerd/linkerd2/pull/2510

**Comment by siggy** [comment]
Merged into https://github.com/linkerd/website/tree/isim/stable-2.4
