### ISSUE TITLE
2.4 - Validate demos and examples in docs

### ISSUE THREAD

**Issue by ihcsim** [linkerd/website#379]
Per conversation with @grampelberg, we need to revisit all the demos and examples in the 'Getting Started' and 'Tasks' docs to make sure they still work. The screenshots should also be updated where necessary,

**Comment by scottcarol** [comment]
Hey @ihcsim, I could take this ticket. To make sure I understand, I would install the latest `edge` version, then run every step in "Getting Started" and then run each step in the "Tasks" section, updating text and screenshots where necessary?

**Comment by grampelberg** [comment]
I’m chugging through this one right now (assigned to myself now!)

**Comment by ihcsim** [comment]
@grampelberg Pretty sure https://github.com/linkerd/website/pull/393 addressed this too, right? Or do you have more in mind?
