### ISSUE TITLE
2.4 - Update the CLI and annotation docs

### ISSUE THREAD

**Issue by ihcsim** [linkerd/website#381]
Use the `linkerd doc` command to generate the list of new CLI commands, to be included in the docs. The following proxy config annotations (which correspond to their CLI options) need to be documented too:

* `config.linkerd.io/disable-identity`
* `config.linkerd.io/debug`
* `config.linkerd.io/proxy-init-version`

**Comment by jonathanbeber** [comment]
also, `config.linkerd.io/proxy-version`  was released on `2.3.0` and it's not listed in the documentation.

**Comment by siggy** [comment]
Merged into https://github.com/linkerd/website/tree/isim/stable-2.4
