### ISSUE TITLE
Add 2.6 Upgrade Notes

### ISSUE THREAD

**Issue by ihcsim** [linkerd/website#540]
This issue captures any items that user needs to be aware of when upgrading to 2.6.

* Command: `linkerd upgrade | kubectl apply --prune  linkerd.io/control-plane-ns=linkerd -f -`
* Any information on `helm upgrade`?
* Users should replace the `linkerd.io/is-control-plane` namespace label, with the new `config.linkerd.io/admission-webhooks: disabled` to ensure pod creation events in these namespaces aren't picked up when the HA proxy injector is unavailable
* Do we need to mention that the `destination` pod is now in its own `Deployment`?
* etc.

**Comment by alpeb** [comment]
> * Users should replace the `linkerd.io/is-control-plane` namespace label, with the new `config.linkerd.io/admission-webhooks: disabled` to ensure pod creation events in these namespaces aren't picked up when the HA proxy injector is unavailable

@ihcsim I believe we ended up leaving the `linkerd.io/is-control-plane` annotation, used by `bin/test-cleanup`

**Comment by ihcsim** [comment]
The MWC is updated to watch only `config.linkerd.io/admission-webhooks`. The `linkerd` namespace has the new label too.

**Comment by cpretzer** [comment]
Small note: the prune command needs the `-l` flag to specify the label:

>  - Command: linkerd upgrade | kubectl apply --prune -l linkerd.io/control-plane-ns=linkerd -f -

**Comment by ihcsim** [comment]
Fixed by https://github.com/linkerd/website/pull/553.
