### ISSUE TITLE
automate install script testing

### ISSUE THREAD

**Issue by siggy** [linkerd/website#552]
Our `install` and `install-edge` scripts are manually reviewed, but not tested during CI. This can cause issues like #550, where the script may work in some environments/shells but not others.

Update CI to run https://www.shellcheck.net on the scripts, and also execute the script to confirm linkerd is correctly installed.

**Comment by grampelberg** [comment]
TIL, this is great. I really wish there was a way to run OSX containers, doing some automated linux testing will be easy.

**Comment by grampelberg** [comment]
Fixed with #554
