### ISSUE TITLE
Document for modifying proxy log level via new endpoint

### ISSUE THREAD

**Issue by ihcsim** [linkerd/website#565]
Update the _Modifying the Proxy Log Level_ doc to show how to change the proxy log level at runtime via the new `/proxy-log-level` endpoint:
```
:; k exec -n emojivoto -it -c linkerd-proxy web-c4d87867-h7sdx  -- curl -v --data 'linkerd2_proxy=info,linkerd2_proxy::proxy::client=debug' -X PUT localhost:4191/proxy-log-level
```

**Comment by cpretzer** [comment]
@ihcsim I ran this command on a new deployment of booksapp on `2.6.0` and got this error:

```error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "92240ca16aa0a1f8565b25297ea608afec0df7b19e9822bfb6a1de11ccf2fa5a": OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"curl\": executable file not found in $PATH": unknown```

When I exec in to the `linkerd-proxy` container and run `curl` I get a similar error.

It feels like I'm missing something here.

**Comment by hawkw** [comment]
> It feels like I'm missing something here.

I think the thing you're missing is `curl` :P

I think that when I wrote that kubectl command out, curl was installed into the proxy container by default, but since then, we removed most of the debug tools.

**Comment by adleong** [comment]
The command should be:

```
:; kubectl port-forward -n emojivoto web-c4d87867-h7sdx  4194 &
:; curl -v --data 'linkerd=debug' -X PUT localhost:4191/proxy-log-level
```

**Comment by adleong** [comment]
We should also update the page to indicate that changing the pod's annotations will not dynamically update the log level and that the log level can only be dynamically updated by using the `/proxy-log-level` endpoint.
