### ISSUE TITLE
distributed tracing docs need to be updated

### ISSUE THREAD

**Issue by wmorgan** [linkerd/website#575]
https://linkerd.io/2/features/distributed-tracing/ claims we don't emit spans (in the TOC).

It also contains no documentation on how to enable distributed tracing, which currently appears to just be documented in a blog post

**Comment by grampelberg** [comment]
Gotchas so far:

- b3 headers are used, so using a jaeger client requires reconfiguration of the propagation format.
- the collector needs to be injected and service accounts have to match.
