### ISSUE TITLE
Server speaks first protocols

### ISSUE THREAD

**Issue by grampelberg** [linkerd/website#59]
Right now we have a list of protocols that use server speaks first in the overview. That is less than ideal. It would be nice to get a full list of protocols together and their support (eg. http fully supported, X not fully supported but no changes and Y needs to be skipped).

**Comment by wmorgan** [comment]
@grampelberg we now have a dedicated supported protocols page, and we've moved this content to a  "TCP Proxying and Protocol Detection" page. Is this sufficient for your porpoises?
