### ISSUE TITLE
linkerd.io/content/2/tasks/customize-install.md contains false info regarding PodPriority

### ISSUE THREAD

**Issue by dayglojesus** [linkerd/website#596]
Per: https://github.com/kubernetes/website/issues/17863

The `kustomize` examples specifying a `PodPriority` are false. One cannot use `system-cluster-critical` or `system-node-critical` in any namespace other than `kube-system`.

Instead, one must define a custom `PriorityClass` :
```
# Where `1000000000` is max. allowable user defined priority 
---
apiVersion: scheduling.k8s.io/v1
description: Used for linkerd pods that must run in the cluster, but can
  be moved to another node if necessary.
kind: PriorityClass
metadata:
  name: linkerd
value: 1000000000
```

**Comment by ihcsim** [comment]
Fixed by #597.
