### ISSUE TITLE
docs not correctly rendering TOC for ingress page

### ISSUE THREAD

**Issue by oskapt** [linkerd/website#615]
[This page](https://linkerd.io/2/tasks/using-ingress/) is correctly rendering `{{% pagetoc %}}` as a list but also appears to be turning it into a code block. The result is that it shows the raw HTML instead of the links to the sections below.

![Screen Shot 2019-12-24 at 12 29 18](https://user-images.githubusercontent.com/171292/71418397-08c7c780-2649-11ea-8428-f1d5f4112825.png)

**Comment by grampelberg** [comment]
Well that's embarrassing. Looks like hugo updated some shortcode syntax on us. Should be fixed now!
