### ISSUE TITLE
Add `--as` CLI flag in docs

### ISSUE THREAD

**Issue by mayankshah1607** [linkerd/website#634]
Seems like the `--as` CLI flag is missing from the [docs](https://linkerd.io/2/reference/cli/). It would be nice to have the above flag documented as : 

| Flag | Usage |
|-------|-----------|
| `--as`| Username to impersonate for Kubernetes operations|

**Comment by importhuman** [comment]
I'll pick this up.

**Comment by cpretzer** [comment]
thanks @importhuman !

**Comment by importhuman** [comment]
@cpretzer the relevant file has `{{< global-flags >}}` where the flags are. I understand this is from Hugo, can you give me some pointers where I should start? 😅

**Comment by cpretzer** [comment]
@importhuman that's a [hugo shortcode](https://gohugo.io/content-management/shortcodes/) and you can find them in the repo [here](https://github.com/linkerd/website/tree/main/linkerd.io/layouts/shortcodes)
