### ISSUE TITLE
Cannot Build the website

### ISSUE THREAD

**Issue by zigmint** [linkerd/website#693]
Hi, I have been trying to build the website but it continuously shows the following error
```
Building sites … WARN 2020/03/22 20:55:27 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
Built in 741 ms
Error: Error building site: TOCSS: failed to transform "scss/styles.scss" (text/x-scss): resource "scss/scss/styles.scss_5ad6f408b0e3e473c748aac88af0ea18" not found in file cache
```
My Hugo version is 
`Hugo Static Site Generator v0.68.0 linux/amd64 BuildDate: 2020-03-21T16:27:56Z`
and I am using  Ubuntu 18.04 if that is relevant.
TIA

**Comment by grampelberg** [comment]
Sorry about that! You'll need to use the extended version of hugo and that warning is harmless.
