### ISSUE TITLE
Linkerd to use kong ingress settings/setup?

### ISSUE THREAD

**Issue by edjwhho** [linkerd/website#697]
Hi there,

Im trying to get linkerd working with kong ingress in AKS, i have following the instructions on the installation and injection instruction but when I try to follow the https://linkerd.io/2/tasks/using-ingress/
I cant find out which annotations to use for kong ingress controller?
can you help please?

---

- Mailing List: https://lists.cncf.io/g/cncf-linkerd-users

- Slack: https://slack.linkerd.io

- Discourse: https://discourse.linkerd.io/

- Twitter: https://twitter.com/linkerd

**Comment by nesl247** [comment]
I'm not sure if it's the best way, but it seems to be fairly simple. I'm in the process of setting this up and testing it.

I added a `KongPlugin` using the `request-transformer` plugin, which adds the `l5d-dst-override` header. Other than that, just add the annotation to the `kong` namespace to have the pods injected, and that was really all I did so far.

**Comment by edjwhho** [comment]
hi,
can you show an example of how you add the annotation to the kong namespace?

**Comment by nesl247** [comment]
This is from pulumi (our IaC tool), but you should get the picture:

```
new k8s.core.v1.Namespace(config.projectName, {
  metadata: {
    annotations: {
      'linkerd.io/inject': 'enabled',
    },
  },
});
```

```
new k8s.apiextensions.CustomResource('linkerd', {
  apiVersion: 'configuration.konghq.com/v1',
  kind: 'KongPlugin',
  metadata: {
    namespace: namespace.metadata.name,
  },
  plugin: 'request-transformer',
  config: {
    add: {
      headers: [pulumi.interpolate`l5d-dst-override:${service.metadata.name}.${namespace.metadata.name}.svc.cluster.local:${service.spec.ports[0].port}`],
    },
  },
});
```

new k8s.networking.v1beta1.Ingress(`${config.projectName}`, {
  metadata: {
    namespace: namespace.metadata.name,
    annotations: {
      'kubernetes.io/tls-acme': 'true',
      'kubernetes.io/ingress.class': `kong-${config.app.visibility}`,
      'konghq.com/plugins': pulumi.interpolate`${kong.linkerdPlugin.metadata.name}`,
      'configuration.konghq.com': pulumi.interpolate`${kong.httpsOnly.metadata.name}`,
    },
  },
  spec: {
    tls: [
      {
        secretName: `${config.projectName}-certificate`,
        hosts: [config.app.hostname],
      },
    ],
    rules: [
      {
        host: config.app.hostname,
        http: {
          paths: [
            {
              path: '/',
              backend: {
                serviceName: service.metadata.name,
                servicePort: service.spec.ports[0].port,
              },
            },
            {
              path: '/_healthcheck',
              backend: {
                serviceName: service.metadata.name,
                servicePort: service.spec.ports[0].port,
              },
            },
          ],
        },
      },
    ],
  },
});

**Comment by edjwhho** [comment]
hi, i did post a similar suggestion on the kong nations and they came back i need to some regex and cant substitue service name.  Also Im using helm charts for deployment.
Please take a look at this link [https://discuss.konghq.com/t/kong-ingress-request-transformer-problem/5606/3](https://discuss.konghq.com/t/kong-ingress-request-transformer-problem/5606/3)

**Comment by nesl247** [comment]
Yeah, you have to hardcode. I'm using pulumi myself, which is the code I showed. So I am able to use variables in pulumi which outputs the raw yaml to send to kubernetes, which has the value hardcoded.

**Comment by edjwhho** [comment]
Thank you for the pulumi example, ive translated to helm charts and it worked.  thank you for the help,  below is a snippet of some of the code.

**kong plugin:**
```apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-request-header-kong
config:
  add:
    headers:
    - "l5d-dst-override:{{ .Values.ingressClass }}-kong-proxy.{{ .Values.nameSpace }}.svc.cluster.local:443"
plugin: request-transformer
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-request-header-frontend
config:
  add:
    headers:
    - "l5d-dst-override:fms-frontend-svc.{{ .Values.nameSpace }}.svc.cluster.local:8080"
plugin: request-transformer
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-request-header-backend
config:
  add:
    headers:
    - "l5d-dst-override:backend-svc.{{ .Values.nameSpace }}.svc.cluster.local:5000"
plugin: request-transformer
```

**ingress:**
```apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: global-route
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
    kubernetes.io/tls-acme: "{{ .Values.ingressTlsAcme }}"
    cert-manager.io/cluster-issuer: "{{ .Values.ingressCertmanager }}"
    acme.cert-manager.io/http01-ingress-class: "{{ .Values.ingressClass }}"
    configuration.konghq.com: global-route
    plugins.konghq.com: add-response-header
spec:
  tls:
    - secretName: {{ .Values.ingressSecretname }}
      hosts:
        - {{ .Values.ingressHost }}
  rules:
    - host: {{ .Values.ingressHost }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Values.frontend.name }}-svc
            servicePort: {{ .Values.frontend.containerPort }}
        - path: /api/backend
          backend:
            serviceName: {{ .Values.backend.name }}-svc
            servicePort: {{ .Values.backend.containerPort }}
