### ISSUE TITLE
Helm install commands fails with Helm3

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/website#730]
Currently, Most helm commands in the helm tutorial use `--name`, which seems depreciated in Helm3 and the install command fails as 
```
Error: unknown flag: --name
```

In Helm3, The install command works as `helm install [NAME] [CHART]`. So, removing the `--name` flag but still keeping the value fixes this.

Should we update the docs to Helm3? or Should we atleast have a note for the same?

@alpeb

**Comment by alpeb** [comment]
Definitely :+1: Default docs to be Helm3-compatible with a small note for v2 and --name :+1:

**Comment by grampelberg** [comment]
Let's get this done for the next release.
