### ISSUE TITLE
Traffic split page broken link

### ISSUE THREAD

**Issue by Waterdrips** [linkerd/website#755]
This page, https://linkerd.io/2/features/traffic-split/ has a link "TrafficSplit API" which links to non existent page on github, think its moved to https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-split/traffic-split-wd.md

### Possible solution
`https://github.com/servicemeshinterface/smi-spec/blob/master/traffic-split.md`  -> `https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-split/traffic-split-wd.md`

github link to docs page: https://github.com/linkerd/website/blob/master/linkerd.io/content/2/features/traffic-split.md
Happy to raise PR if it helps, just let me know

**Comment by cpretzer** [comment]
thanks for the issue @Waterdrips We'd love a PR if you're up for it! 👍
