### ISSUE TITLE
Gitops with Linkerd

### ISSUE THREAD

**Issue by grampelberg** [linkerd/website#757]
Deploying and managing Linkerd in a fully gitops fashion can be a little confusing. Let's get a example up in the [repo](https://github.com/linkerd/linkerd-examples) that runs through the full walkthrough as part of a Makefile or set of scripts. The end goal of this is to write some documentation for the website, for now it should be an example repo that someone can run through themselves.

# Demo

1. Run git server on cluster
    - Show pulling and pushing from repo
1. Install flux
    - Show flux running
1. Install [helm-operator](https://github.com/fluxcd/helm-operator-get-started)
    - Show helm operator running.
1. Configure flux to use on-cluster git server
    - Show flux syncing on-cluster git server
1. Create linkerd certificates
    - Show certificate details
1. Setup cert-manager
    - Validate cert-manager install
1. Add linkerd certificates to cluster via cert-manager (is there a way to manage cert-manager via gitops?).
    - Show cert-manager created certificates, inspect to see what they look like.
1. Add linkerd configuration to repo (via helm operator).
    - Show control plane deploying, validate with `check`.
1. Add emojivoto to repo.
    - Show emojivoto metrics via linkerd dashboard.

## Extra credit

1. Upgrade linkerd control-plane
    - Validate new version has been installed
1. Upgrade proxy version in the data-plane
    - Validate new version has been installed.

# Requirements

- It should be possible to cut/paste each step (multiple cut/pastes are fine). Users shouldn't need to go figure out how to set something up, instead they should have it setup on their cluster for them. This is the reasoning behind putting a git server on the user's cluster for them.
- Every step needs validation. It should be clear to the user that they have successfully completed the step and provide a way for them to understand exactly what that step did for them.

**Comment by ihcsim** [comment]
A sample repo can be found at https://github.com/ihcsim/linkerd2-gitops. Review required for https://github.com/ihcsim/linkerd2-gitops/pull/1.

cc @grampelberg
