### ISSUE TITLE
Add documentation for add-ons

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/website#801]
Currently, there is no documentation for the add-ons as a concept in general, thus causing confusion on what is supported, and what configuration is allowed.

**Comment by Pothulapati** [comment]
We added the following doc recently around this https://linkerd.io/2/tasks/enabling-addons/

@grampelberg Should we add anything more or is it enough?

**Comment by snnsnn** [comment]
@Pothulapati Links are broken in https://linkerd.io/2/tasks/enabling-addons/. Please can you also discuss how we can implement our own add-ons.

**Comment by Pothulapati** [comment]
Hey @snnsnn, The links are broken because add-ons have been changed into extensions with some architectural changes, and thus the removal of some of those resources.

The new extensions are docs still being worked on. Feel free to take a look at https://github.com/linkerd/linkerd2/pull/5692 to understand more.

**Comment by wmorgan** [comment]
This was done.
