### ISSUE TITLE
Fix shell line in automatic certificate rotation task

### ISSUE THREAD

**Issue by cpackingham** [linkerd/website#825]
The line of bash at the bottom of [automatically rotating control plane tls credentials](https://linkerd.io/2/tasks/automatically-rotating-control-plane-tls-credentials/#installing-with-helm) is not runnable - the name of the helm chart should be on the same line as `helm install`. Pretty minor thing but also easy to fix!

**Comment by grampelberg** [comment]
@cpackingham we'd love a PR if you're up for it!
