### ISSUE TITLE
Update docs with headless service implications

### ISSUE THREAD

**Issue by grampelberg** [linkerd/website#833]
As part of the discovery changes in 2.9, we need to update the docs to mention implications around headless services.

- Add headless service caveats to:
    - Load balancing docs
    - Service profile docs
    - Traffic Split docs
    - Retries docs
    - Timeouts docs
- Update books example to use cluster ip services (and go through the per-route metrics docs to make sure they work).
- Validate the per-route metrics blog post still works

Is there a better place to put the caveats for this? Adding to every docs page seems fragile and prone to breakage.

**Comment by kleimkuhler** [comment]
Closed by linkerd/website#842
