### ISSUE TITLE
Need to detail few steps in https://linkerd.io/2/tasks/exposing-dashboard/

### ISSUE THREAD

**Issue by balajivenkkatesh** [linkerd/website#889]
Would be useful to add a step for adding DNS or host name record for exposing dashboard.
Also, in the nginx YAML file there is a entry - nginx.ingress.kubernetes.io/upstream-vhost: $service_name.$namespace.svc.cluster.local:8084

Can be descriptive if the service_name and namespace variables need to be assigned before using or it should be replaced appropriately.

**Comment by adleong** [comment]
Hi @balajivenkkatesh!  The process to add a DNS record which points to where you have the Linkerd dashboard exposed will be different depending on your cloud environment.  Please refer to the documentation for your cloud environment.

**Comment by balajivenkkatesh** [comment]
> Hi @balajivenkkatesh! The process to add a DNS record which points to where you have the Linkerd dashboard exposed will be different depending on your cloud environment. Please refer to the documentation for your cloud environment.

Hi @adleong ,
The DNS entry is a common process across cloud wherein a CNAME or A record is created. So I dont believe there is anything cloud specific. Also, if we could suggest adding a host file entry in sandbox for validation, even that will help.
There is a another question I have asked which is missed out related to upstream-vhost. Could you please review that as well.
