### ISSUE TITLE
Detailing of few comfiguration mentioned in YAML file under https://linkerd.io/2/tasks/exposing-dashboard/

### ISSUE THREAD

**Issue by balajivenkkatesh** [linkerd/website#893]
**$service_name.$namespace**.svc.cluster.local:8084
Can be descriptive if the service_name and namespace variables need to be assigned before using or it should be replaced appropriately.

**Comment by alpeb** [comment]
`$service_name` and `$namespace` are variables that are set by Nginx itself. So the sample in the docs should be used as-is, without having to replace anything.

**Comment by adleong** [comment]
@balajivenkkatesh I'm closing this issue thanks to @alpeb's answer.  If that doesn't answer your question, please feel free to open another issue.
