### ISSUE TITLE
Automatic mTLS example does not work

### ISSUE THREAD

**Issue by martja** [linkerd/website#923]
In the [Automatic mTLS example](https://linkerd.io/2/tasks/automatically-rotating-control-plane-tls-credentials/), the secret generated by cert-manager has a suffix. In my case it is called `linkerd-identity-issuer-bjmwc`. When running `linkerd install --identity-external-issuer` this causes an error `Error: secrets "linkerd-identity-issuer" not found`.

[This issue](https://github.com/jetstack/cert-manager/issues/3283) in cert-manager might be related.

**Comment by cpretzer** [comment]
Thanks for the report @martja, The `cert-manager` issue does appear to be related.

**Comment by martja** [comment]
This was an error with the cert-manager installation on my part. The example works fine.

**Comment by mattskone** [comment]
> This was an error with the cert-manager installation on my part.

@martja What specifically was the error with the cert-manager installation?

**Comment by martja** [comment]
Good question @mattskone... Looking through my git history I think the issue was me trying to use http-01 challenge with letsencrypt while also only allowing a whitelisted range of IP-addresses into my cluster. The solution was to use dns-01 through a webhook.
