### ISSUE TITLE
Create a doc for rolling back from 2.9.x release

### ISSUE THREAD

**Issue by ericsuhong** [linkerd/website#949]
2.9.x linkerd introduced configuration structure changes, and it does not allow you to rollback using linkerd CLI easily (linkerd CLI will throw panic as mentioned here: https://github.com/linkerd/linkerd2/issues/5639)

I would like to see some kind of "warning" that 2.9.x linkerd introduces this issue and a clear doc for rolling back from 2.9.x if possible.

**Comment by adleong** [comment]
Unfortunately, there is no easy way to rollback past this configuration structure change.  I recommend rolling forward to stable-2.9.3 or later and using the `linkerd repair` command to fix any configuration problems.

**Comment by ericsuhong** [comment]
Hi, Alex. It would be super helpful for users if linkerd doc clearly warns about that it is not possible to roll back to 2.8.x once you upgrade to 2.9.x.

If I knew that it was not easy to roll back to 2.8.x from 2.9.x, I would have made a much more cautious approach.

**Comment by adleong** [comment]
That's totally fair.  Are you interested in contributing a website PR to help us clarify this?

**Comment by adleong** [comment]
Please open a PR against https://github.com/linkerd/website if you're interested in helping us clarify this.
